import { cloudflare } from '@cloudflare/vite-plugin'
import { reactRouter } from '@react-router/dev/vite'
import { sentryVitePlugin } from '@sentry/vite-plugin'
import { glob } from 'glob'
import { defineConfig } from 'vite'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig(async () => {
	const plugins = [
		cloudflare({ viteEnvironment: { name: 'ssr' } }),
		reactRouter(),
		tsconfigPaths(),
		sentryVitePlugin({
			telemetry: false,
			authToken: process.env.SENTRY_AUTH_TOKEN,
			org: process.env.SENTRY_ORG,
			project: process.env.SENTRY_PROJECT,
			release: {
				name: process.env.COMMIT_SHA,
				setCommits: {
					auto: true,
				},
			},
			sourcemaps: {
				// Only delete client-side maps after upload. Server-side maps must
				// remain on disk so Wrangler can resolve sourceMappingURL references
				// in the worker entry shim and modules generated by @cloudflare/vite-plugin.
				filesToDeleteAfterUpload: await glob(['./build/client/**/*.map', '.server-build/**/*.map']),
			},
		}),
	]

	return {
		plugins,

		ssr: { noExternal: 'react-h5-audio-player' },

		server: {
			port: 8080,
			fs: {
				allow: ['app', 'node_modules'],
			},
		},

		build: {
			sourcemap: true,
		},
	}
})
