// Generated by Wrangler on Mon Mar 11 2024 14:25:35 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	CACHE_CONTROL: 'no-store'
	DATABASE_URL: 'prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTkyNTk5Y2ItZmRhYS00YjNmLWJlY2MtOTU3NTQ4YWE4NzUzIiwidGVuYW50X2lkIjoiYTZmZDliNWM0MTE4ZDNmNTEwNWM0NmU2Mzg2YjlkMzY0MDVlZTUwZDI4N2NhODRlOGZhMmFhNDczY2FlYWNmNiIsImludGVybmFsX3NlY3JldCI6IjNiZmQxOTA1LWRlNDMtNGVlOS05YzJhLTMwYWNmZWNhNjEzMCJ9.1FTpj2pIFxrGIpbJ9SxGBi_TcM_TZG6FHIpaoKvr-B8'
	STORAGE_BUCKET: R2Bucket
}
