// Generated by Wrangler on Sun Mar 10 2024 21:27:36 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	CACHE_CONTROL: "no-store";
	DATABASE_URL: "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTkyNTk5Y2ItZmRhYS00YjNmLWJlY2MtOTU3NTQ4YWE4NzUzIiwidGVuYW50X2lkIjoiYTZmZDliNWM0MTE4ZDNmNTEwNWM0NmU2Mzg2YjlkMzY0MDVlZTUwZDI4N2NhODRlOGZhMmFhNDczY2FlYWNmNiIsImludGVybmFsX3NlY3JldCI6IjNiZmQxOTA1LWRlNDMtNGVlOS05YzJhLTMwYWNmZWNhNjEzMCJ9.1FTpj2pIFxrGIpbJ9SxGBi_TcM_TZG6FHIpaoKvr-B8";
	STORAGE_BUCKET: R2Bucket;
}
